package com.vidyasagar.attendance.api.v1.repository;

import com.vidyasagar.attendance.entity.Student;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface StudentRepository extends JpaRepository<Student, Long>, JpaSpecificationExecutor<Student> {
    // you get CRUD methods for free: save, findById, findAll, deleteById

    // Derived queries (auto-generated by Spring)
    List<Student> findByName(String name);
    List<Student> findByAgeGreaterThan(int age);

    // Custom JPQL query
    @Query("SELECT s FROM Student s WHERE s.email LIKE %?1%")
    List<Student> findByEmailContains(String keyword);

    // Native SQL example
    @Query(value = "SELECT * FROM student2s WHERE name ILIKE %?1%", nativeQuery = true)
    List<Student> searchByName(String namePart);
}
